//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenData.Console.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIR_QUALITY
    {
        public int ID_AIR_QUALITY { get; set; }
        public decimal GPS_X { get; set; }
        public decimal GPS_Y { get; set; }
        public decimal TEMPERATURE { get; set; }
        public decimal HUMIDITE { get; set; }
        public int CO2 { get; set; }
        public int PRESSION_ATMO { get; set; }
    }
}
