//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenData.Console.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class METEO_JOUR
    {
        public int ID_METEO_JOUR { get; set; }
        public System.DateTime DATE { get; set; }
        public string VALIDITE { get; set; }
        public string DESC_GLOBAL { get; set; }
        public string DESC_WIND { get; set; }
        public string DESC_HUMIDITE { get; set; }
        public string SUNRISE { get; set; }
        public string SUNSET { get; set; }
        public string MOONRISE { get; set; }
        public string MOONSET { get; set; }
        public string DESC_ROAD { get; set; }
    }
}
