//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenData.Console.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUSEE
    {
        public int ID_MUSEE { get; set; }
        public string NOM { get; set; }
        public decimal GPS_X { get; set; }
        public decimal GPS_Y { get; set; }
    }
}
