//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockCycle.UI.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlockChainEntities : DbContext
    {
        public BlockChainEntities()
            : base("name=BlockChainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<METEO> METEO { get; set; }
        public virtual DbSet<METEO_JOUR> METEO_JOUR { get; set; }
        public virtual DbSet<AIR_QUALITY> AIR_QUALITY { get; set; }
        public virtual DbSet<PISTE_CYCLABLE_DETAIL> PISTE_CYCLABLE_DETAIL { get; set; }
        public virtual DbSet<PISTE_CYCLABLE_ENTETE> PISTE_CYCLABLE_ENTETE { get; set; }
        public virtual DbSet<PISTE_VTT_DETAIL> PISTE_VTT_DETAIL { get; set; }
        public virtual DbSet<PISTE_VTT_ENTETE> PISTE_VTT_ENTETE { get; set; }
        public virtual DbSet<MUSEE> MUSEE { get; set; }
    }
}
