//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockCycle.UI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PISTE_CYCLABLE_ENTETE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PISTE_CYCLABLE_ENTETE()
        {
            this.PISTE_CYCLABLE_DETAIL = new HashSet<PISTE_CYCLABLE_DETAIL>();
        }
    
        public int ID_PISTE_CYCLABLE_ENTETE { get; set; }
        public string NOM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PISTE_CYCLABLE_DETAIL> PISTE_CYCLABLE_DETAIL { get; set; }
    }
}
